version: '3.8'

services:
  api:
    build: .
    ports:
      - "5050:5050"
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USERNAME=postgres
      - DB_PASSWORD=root
      - DB_NAME=db_car-go
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_car-go
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
